
spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatty
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # a day

logging:
  level:
    org.springframework.security: DEBUG
    com.chatty.auth: DEBUG
