
spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatty
      auto-index-creation: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.chatty.customer: DEBUG
